### ISSUE TITLE
redirect website url

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocols#1]
Currently, the https://protocols.inbo.be/ url does not redirect to https://inbo.github.io/protocols/. 
See also https://github.com/inbo/protocolsource/pull/19#issuecomment-653026135.

@ThierryO @aaikedw do you know how to do this?

**Comment by ThierryO** [comment]
I think @peterdesmet knowns the solution.

**Comment by peterdesmet** [comment]
Not something I can fix. 😄  Please email ICT helpdesk (@berthuygens).

It looks like `protocols.inbo.be` is currently configured to rewrite to `inbo.github.io` rather than `inbo.github.io/protocols`. It should be configured similarly to `oscibio.inbo.be`

**Comment by berthuygens** [comment]
fixed!  (refresh maybe needed)

**Comment by hansvancalster** [comment]
Bedankt @berthuygens
