### ISSUE TITLE
Readme: fixed protocol features miss 'protocol_number'

### ISSUE THREAD

**Issue by florisvdh** [inbo/protocols#16]
`protocolhelper::create_sfp()` has an argument `protocol_number`. As the function documentation is not clear about what that is, I think this should be present in the general documentation of fixed protocol features.

**Comment by hansvancalster** [comment]
I think the function documentation is clear: 
```` 
#' A character string giving the protocol number.
#' This parameter should normally not be specified (i.e. NULL), unless
#' `from_docx` is specified.
#' A protocol number is a three digit string where the first digit corresponds
#' with a theme and the last two digits identify a protocol within a theme.
#' If NULL (the default), a protocol number will be determined automatically
#' based on pre-existing protocol numbers.
#' Protocol numbers that are already in use can be retrieved with
#' `get_protocolnumbers()`.
````
?

**Comment by florisvdh** [comment]
:+1:  I should have looked better, sorry. (I was blinded by the `from_docx` syntax highlighting on a newline, in RStudio)

Still, I suggest to centralize all the vocabulary in the readme; the term "protocol number", referring to the three digits, is currently not present as such.

**Comment by hansvancalster** [comment]
See https://github.com/inbo/protocols/pull/15 commit 697f7b8
