### ISSUE TITLE
reviewing guidelines

### ISSUE THREAD

**Issue by ToonHub** [inbo/protocols#25]
I wanted to request a review from a thematic expert (who is not very familiar with github) but I was not sure what reviewing guidelines I would suggest to him. The current guidelines are a bit vague.

I think that for commenting on text and suggesting changes following guidelines are the most straightforward and transparent:
[https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request](url)
We could add these guidelines (the link) in the pull request template message?

For commenting on images I would suggest to add a comment directly in the pull request.

I also think it would be a good idea to push the rendered html-file to the branch, to link to this file in the pull request and to give instructions on downloading and opening this file. This way the reviewer gets a good overview of the protocol without having to build it in Rstudio. Or should we avoid pushing html-files to the repo? Alternatively we could just send it by email.

In case we do work in Rstudio to review a pull request, what is the best way to make a suggested change. Do we commit the suggested changes in a new branch and make a new pull request?

**Comment by florisvdh** [comment]
My two cents on this:

- agree to refer to clear guidelines if they match the workflow
- don't push html files in the protocols repo
- do attach a zipped website in the pull request (which you can keep updating as commits are added, by editing the message). You can attach files here (drag and drop), they're not included in the repo. See https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

**Comment by hansvancalster** [comment]
I think this can be closed as the GHA workflow adds an artifact with a zip file containing the html version. Also the REVIEWING.md file mentions https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request
