### ISSUE TITLE
NEWS.md

### ISSUE THREAD

**Issue by ThierryO** [inbo/protocols#4]
We should have a bunch of NEWS.md files

- One at the root describing the overal changes in the repo. One entry for each release describing the generic changes since the previous release.
```
2020-04-15: Updated protocol A
2020-03-21: Added protocol B
2020-03-20: Added protocol A
```
- One next to each protocol. Describing the changes in the protocol in detail.
```
2020-04-15: Fixing some typo's
2020-03-20: First version of the protocol
```

**Comment by hansvancalster** [comment]
Good idea. I've added an empty NEWS.md to the root and added a to-be-written section in README.md about this. The project specific NEWS.md will need to be part of the function that starts a new protocol.

**Comment by hansvancalster** [comment]
This is now incorporated in the `protocolhelper::create_sfp()` function
